### PR TITLE
Sponsors

### PR DESCRIPTION
**Pull request by gingermusketeer**
Todo:
- [x] Update list of sponsors we have.
- [x] Update packages we can offer.

### CODE REVIEW

**Comment by gingermusketeer** [comment]
@Andersos Do you have a list of the sponsors we have signed up and packages that we are offering?

**Comment by Andersos** [comment]
Sent you on Slack =)

**Comment by gingermusketeer** [comment]
@Andersos Can you review the content and what I have done with the links? I didn't find a link for Cisco.

**Review by Andersos — APPROVED** [review]
Looks good!

**Pull request merged**
