### PR TITLE
Change the landing page to say `We're back`

### PR DESCRIPTION
**Pull request by stoivo**
Screenshot 2020-01-28 at 19 08 55
Screenshot 2020-01-28 at 19 05 34

### CODE REVIEW

**Comment by stoivo** [comment]
@gingermusketeer should we deploy this?

**Comment by gingermusketeer** [comment]
I am wondering if we should have something like “webrebels 2020” or maybe we should include “Oslo” for new people?

**Comment by gingermusketeer** [comment]
“We’re back 2020” makes it sound like it is happening next year

**Comment by gingermusketeer** [comment]
This is an improvement so I am going to merge :)

**Pull request merged**
